# Generated by Django 4.2.4 on 2023-09-28 06:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last modified time')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='category name')),
                ('index', models.IntegerField(default=0, verbose_name='order by larger num')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='create time')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last modified time')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='title')),
                ('body', mdeditor.fields.MDTextField(verbose_name='article content')),
                ('pub_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='publish time')),
                ('status', models.CharField(choices=[('d', 'draft'), ('p', 'publish')], default='d', max_length=1, verbose_name='article status')),
                ('article_order', models.IntegerField(default=0, verbose_name='order by larger num')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
